---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ztp-aap-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ztp-aap-rbac
subjects:
- kind: ServiceAccount
  name: ztp-aap-sa
  namespace: ztp-aap-integration
